### ISSUE TITLE
Helpful error message when user forgets to run `argospm update`

### ISSUE THREAD

**Issue by PJ-Finlay** [argosopentech/argos-translate#103]
```
$ argospm install translate-en_es
Traceback (most recent call last):
  File "/home/argosopentech/onmt-models/env/lib/python3.8/site-packages/argostranslate/package.py", line 216, in get_available_packages
    with open(settings.local_package_index) as index_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/argosopentech/.local/cache/argos-translate/index.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/argosopentech/onmt-models/env/bin/argospm", line 5, in <module>
    argospm.main()
  File "/home/argosopentech/onmt-models/env/lib/python3.8/site-packages/argostranslate/argospm.py", line 108, in main
    args.callback(args)
  File "/home/argosopentech/onmt-models/env/lib/python3.8/site-packages/argostranslate/argospm.py", line 29, in install_package
    available_packages = package.get_available_packages()
  File "/home/argosopentech/onmt-models/env/lib/python3.8/site-packages/argostranslate/package.py", line 224, in get_available_packages
    raise Exception('Local package index not found,' +
Exception: Local package index not found, use package.update_package_index() to load it
```

**Comment by dingedi** [comment]
Maybe it's easier to automatically update the package list if the user has forgotten `argospm update` before `argospm install` or `argospm search`?

**Comment by PJ-Finlay** [comment]
Yes auto updating if there isn't already a local package index is probably a good idea.

**Comment by dingedi** [comment]
Done here [https://github.com/argosopentech/argos-translate/pull/178](https://github.com/argosopentech/argos-translate/pull/178)

**Comment by xiaohongzsy** [comment]
Could you tell  me the solution when input the example of python error,thanks！：）
![image](https://user-images.githubusercontent.com/58612570/205670641-c523e7f1-5a1d-4cf8-9413-3a15c90360b5.png)
发生异常: Exception
Local package index not found, use package.update_package_index() to load it

During handling of the above exception, another exception occurred:

  File "E:\UAV sofewave\text fangyi .py", line 8, in <module>
    available_packages = argostranslate.package.get_available_packages()
    
    # Download and install Argos Translate package
available_packages = argostranslate.package.get_available_packages()
package_to_install = next(
    filter(
        lambda x: x.from_code == from_code and x.to_code == to_code, available_packages
    )
)
argostranslate.package.install_from_path(package_to_install.download())

**Comment by xiaohongzsy** [comment]
![image](https://user-images.githubusercontent.com/58612570/205675366-f22cadd8-c647-4f1f-ad34-82de94264551.png)

**Comment by PJ-Finlay** [comment]
You need to call:
```
argostranslate.package.update_package_index()

```

**Comment by PJ-Finlay** [comment]
Sorry the documentation was confusing so I [updated it](https://github.com/argosopentech/argos-translate/commit/3d229c84bf6bcf10e92065ee583eecb60a44ea16).
