### ISSUE TITLE
argostranslate and raspberry pi

### ISSUE THREAD

**Issue by akmalkady** [argosopentech/argos-translate#112]
Hi

I have a python script that I suppose to run in a raspberry pi, but I couldn't since it requires argostranslate.
The issue is that argostranslate requires PyQt5, and I couldn't install PyQt5 in my raspberry pi.

I don't need PyQt5 since I don't need argostranslate GUI.

Is there any way to install a copy of argostranslate that doesn't require PyQt?

This is the command I used to install argostranslate:
`python3 -m pip install argostranslate
`
Here is the OS info:
`Linux raspberrypi 4.19.127v64 #1 SMP PREEMPT Fri Jun 12 22:09:51 CEST 2020 aarch64 GNU/Linux
`

**Comment by akmalkady** [comment]
I just realized that the issue is not with PyQt. It is with sentencepiece.
More details here:
https://github.com/google/sentencepiece/issues/584

I don't know how to fix this issue

**Comment by PJ-Finlay** [comment]
This seems like an issue with installing SentencePiece on ARM not specific to Argos Translate.

Based on the issue you linked it looks like you need to download the aarch64 release from the [SentencePiece release page](https://github.com/google/sentencepiece/releases) and install it before installing Argos Translate. Argos Translate [currently uses](https://github.com/argosopentech/argos-translate/blob/master/requirements.txt)  `sentencepiece==0.1.94`  so you will want to download ` sentencepiece-0.1.94-cp35-cp35m-manylinux2014_aarch64.whl`.

To [install a Python Wheel](https://stackoverflow.com/questions/28002897/wheel-file-installation):
```
pip install sentencepiece-0.1.94-cp35-cp35m-manylinux2014_aarch64.whl
```
