### ISSUE TITLE
Cite this project

### ISSUE THREAD

**Issue by pitehu** [argosopentech/argos-translate#116]
This project has been helpful to my research and I would like to cite it should there be a publication opportunity. Could you provide a bib file so that I can properly cite?

**Comment by PJ-Finlay** [comment]
```
@misc{
   author = {P.J. Finlay},
   title = {Argos Translate},
   url = {https://www.argosopentech.com},
   note = {Open source neural machine translation software}
}
```

Glad you found it useful! Please post if you publish I'd be curious to read about how you used the project.
