### ISSUE TITLE
Error: 'en' is not an installed language. // Mac os

### ISSUE THREAD

**Issue by AnatoliyAkhmatov** [argosopentech/argos-translate#138]
Argos cant packages in ~/.local/share/argos-translate/packages, but they are there

![image](https://user-images.githubusercontent.com/25587346/123677558-16c25e00-d867-11eb-8ad0-aa735ddf164f.png)

**Comment by AnatoliyAkhmatov** [comment]
Fuck... need the unzip each model

**Comment by PJ-Finlay** [comment]
Packages are downloaded to `~/.local/cache/argos-translate/downloads/` then unzipped into `~/.local/share/argos-translate/packages/`. See [XDG Spec](https://wiki.archlinux.org/title/XDG_Base_Directory).
