### ISSUE TITLE
Help Wanted: Mac Screenshots

### ISSUE THREAD

**Issue by argosopentech** [argosopentech/argos-translate#139]
The Mac App Store requires screenshots 1280x800, 1440x900, 2560x1600, or 2880x1800. 

The dev machine is a mac mini connected to a monitor that can't output any of those resolutions. To get the Mac app either install from pip and use the dev package index with Stanza disabled `export ARGOS_STANZA_AVAILABLE=0; export ARGOS_DEV_MODE=1` or [download the Mac version](https://www.fulfillment.argosopentech.com/argos-translate/macos/1981867401692101689462823333574892722487703316879849724390796876302268929269575834660004918158927127779617803719686848953512695878948840276478203680869921/).

Any help appreciated, thanks!

**Comment by pierotofy** [comment]
You may also be able to follow this tip (the `Simplest solution` answer, by pressing the option key) https://apple.stackexchange.com/a/344836 and then VNC onto the Mini at the resolution you need.

**Comment by PJ-Finlay** [comment]
Thanks for the link, I tried the option key solution but still didn't have any of the required resolutions as options. I'm planning to try VNC.

**Comment by PJ-Finlay** [comment]
I have VNC working but can't set the resolution there either. 🤷

https://www.reddit.com/r/MacOS/comments/odtkcf/setting_vnc_resolution_macos/

**Comment by pierotofy** [comment]
Ugh, Apple. :laughing: 

I wish I could help, I also have a Mac Mini and a monitor with low resolution.

**Comment by PJ-Finlay** [comment]
🎉

<img width="1440" alt="Screen Shot 2021-07-10 at 8 11 25 PM" src="https://user-images.githubusercontent.com/13067016/125197218-610dec80-e222-11eb-98ef-72d55a5b2720.png">
