### ISSUE TITLE
Packages window doesn't handle resizing well

### ISSUE THREAD

**Issue by PJ-Finlay** [argosopentech/argos-translate#14]
![image](https://user-images.githubusercontent.com/13067016/102836646-82f76d00-43bf-11eb-8431-095d8bfe9ead.png)

**Comment by JulienMaille** [comment]
I saw you use PyQt gorgeous through GUi. This typically happens when you use designer and forget to set a layout to the the top level widget

**Comment by PJ-Finlay** [comment]
It looks like the top level package widget does have its layout set. I think the solution is going to be either having the inner widgets scale, or blocking the entire window from being scaled.
https://github.com/argosopentech/argos-translate/blob/0ae69e010da06cf7a5858c410ad72bddf131b9a8/argostranslate/gui.py#L29-L51

**Comment by ederin** [comment]
![responsive-package-window](https://user-images.githubusercontent.com/72567273/102946319-92aaaa80-44c0-11eb-9903-87f741017911.png)

**Comment by PJ-Finlay** [comment]
Closing, big thanks to @ederin!
