### ISSUE TITLE
Models in PyTorch or TensorFlow

### ISSUE THREAD

**Issue by solmersa** [argosopentech/argos-translate#142]
As ctranslate2, does not run on Windows or is not built by default, those converted models are not usable on Windows, It would be very useful to have available the PyTorch or TensorFlow Models so be could deploy them on Windows, while #84 gets fixed.

**Comment by PJ-Finlay** [comment]
The models are only saved in quantized and converted format so the easiest way to run on Windows is probably to compile CTranslate2 or use containers/virtualization.
