### ISSUE TITLE
Set for worlds , which are not in dictionaries

### ISSUE THREAD

**Issue by stabud** [argosopentech/argos-translate#166]
Hi!

If it's not difficult, then I would like to have an option in the settings that would regulate: to translate or not to translate those words that are not in the dictionary.

For example, now the translation into Russian of such a phrase:

> this freerrrrr!

looks like that:
 
 >Это бесплатно!
 
 But it's not right! The word **freerrrrr!** is not in the dictionaries, but it is truncated and part of the word is translated.
 
It would be correct to translate only the word that is in the dictionary, and leave the other word as it is:
 
 >Это freerrrrr!!

**Comment by PJ-Finlay** [comment]
Unfortunately this is not straightforward.

There is not dictionary, instead there's a neural net that maps source to target translation. Hopefully as the neural nets improve they'll get better at recognizing what they shouldn't attempt to translate but mistakes still happen.


This script allows you to override specific translations though:

https://community.libretranslate.com/t/how-to-override-few-translation/22/6

**Comment by PJ-Finlay** [comment]
You can also use ITranslation.hypotheses to exclude entire sentences the neural net isn't confident about.

**Comment by stabud** [comment]
It's clear. Apart from the preliminary user code (filtering words before starting translation), there is no way to influence the situation. Thanks for the answer!
