### ISSUE TITLE
Partnership

### ISSUE THREAD

**Issue by grupoastian** [argosopentech/argos-translate#171]
We have been one of the first organizations to deploy a public instance of [LibreTranslate](translate.astian.org) even without modifications and we are very very grateful for the service that has received a very positive reception and every day people use it more.

We would like to establish a partnership to have an impulse to deliver both organizations and we can build an excellent service.

Support
Use in other applications
marketing
etc

**Comment by grupoastian** [comment]
@PJ-Finlay We have passed your email to our CEO, he will contact you soon, you are the founder and director of Argos and Libre Translate right?

**Comment by PJ-Finlay** [comment]
Sounds good! I wrote and maintain Argos Translate and am very involved in the LibreTranslate project. @pierotofy is the primary maintainer of LibreTranslate.

**Comment by pierotofy** [comment]
Which wouldn't exist if it wasn't for Argos Translate :)

**Comment by dingedi** [comment]
Hello I noticed that your instance is fast enough to translate text, for 2000 characters yours takes about 15 seconds (very long compared to google etc but much faster than mine instance which takes more than one minute and 40 seconds ! )
what is the configuration of your server?
