### ISSUE TITLE
Snap Package does not work on Manjaro Linux KDE

### ISSUE THREAD

**Issue by marreromarco** [argosopentech/argos-translate#187]
The Snap Package (1.4.0) doesn't work on the latest edition of Manjaro Linux KDE. The Snap cannot run after installation. That is, the GUI does not appear.

I am afraid that the Snap version does not offer any hint about what is the error.

 If there is a way to debug, I would be glad to help as much as possible.

Thanks in advance for your kind help….

**Comment by PJ-Finlay** [comment]
That's strange, snaps should be very portable between distros. Can you try running from the command line to see if it prints anything?

**Comment by marreromarco** [comment]
![2021-09-19_17-36](https://user-images.githubusercontent.com/58692066/133943782-0171ba62-dc17-4ef5-ada1-0e313c8c8893.png)

**Is there a way to solve that issue ?**

I am not a technical user, but I would be glad to help as much as possible !

**Comment by PJ-Finlay** [comment]
It looks like a caching bug with Snap and Manjaro not Argos Translate related.
