### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by dingedi** [argosopentech/argos-translate#192]
I often spot translation errors, is it useful to add them in [https://github.com/argosopentech/argos-parallel-corpus](https://github.com/argosopentech/argos-parallel-corpus) ?

Exemple:
![image](https://user-images.githubusercontent.com/64697405/135223307-1898d348-4ba8-4532-ac8f-e161664352b0.png)
but no problem without upper case
![image](https://user-images.githubusercontent.com/64697405/135223401-c8021f78-5dfd-4533-92a0-d67ff9bfe72c.png)

and another one

![image](https://user-images.githubusercontent.com/64697405/135223509-ed51b960-0660-4c6e-b8d2-0a448c32bf5b.png)
" Vendredi " is friday in french

**Comment by PJ-Finlay** [comment]
It's essentially an empty repo currently but I think collecting high quality translations could be useful.

**Comment by pierotofy** [comment]
Long term some sort of web-UI to make corpus contributions easier might help build a high quality database. (Would be a cool idea for a contribution @dingedi )

**Comment by dingedi** [comment]
> Long term some sort of web-UI to make corpus contributions easier might help build a high quality database. (Would be a cool idea for a contribution @dingedi )

Yes i think too, i was actually thinking of doing that and adding it directly to LibreTranslate.

**Comment by PJ-Finlay** [comment]
What we'd want to do is collect parallel sentences and publish them. Then Argos Translate, and other projects, could train using that data. The most straightforward way to collect data would be an interface in the LibreTranslate web UI. We could then either auto upload the data to a central server or collect it on the server and have the server admin send it to a git repo or something.
