### ISSUE TITLE
Running with PHP script shell_exec

### ISSUE THREAD

**Issue by matbht** [argosopentech/argos-translate#198]
Hi,

I'm having issues about something:

In CLI it's working fine:
`argos-translate --from-lang en --to-lang fr "Hello World"`

But in php when doing it via NGINX + FPM it's saying:
```
$exec = 'argos-translate --from-lang '.$from.' --to-lang '.$to.' "'.$string.'" 2>&1';
$translatedText = shell_exec($exec);
```

usage: argos-translate [-h] [--from-lang FROM_LANG] [--to-lang TO_LANG] [TEXT]\nargos-translate: error: 'en' is not an installed language.\n

All languages are installed, any idea to put a path for the languages?

How I could fix this

Thanks

**Comment by PJ-Finlay** [comment]
I'm guessing this is an issue with the $PATH or $HOME environment preventing it from finding the [packages directory](https://github.com/argosopentech/argos-translate/blob/20dbd3d823ca20637c3b58d2f1abdd786141bed9/argostranslate/settings.py#L30)
