### ISSUE TITLE
when DownloadPackagesWindow list too many packages, the window became too big to be seen on small devices.

### ISSUE THREAD

**Issue by fcolecumberri** [argosopentech/argos-translate#209]
I think this could be fixed putting the PackagesTable of DownloadPackagesWindow inside a scrollArea

**Comment by PJ-Finlay** [comment]
I think this is fixed in source, should get pushed out before too long.

https://github.com/argosopentech/argos-translate/commit/825dd4287b0c747d4f097391548400bfee7feb52

**Comment by PJ-Finlay** [comment]
Just pushed 1.5.3 to PyPI, this should be fixed.
