### ISSUE TITLE
How to set cuda device from in python script?

### ISSUE THREAD

**Issue by fcolecumberri** [argosopentech/argos-translate#210]

**Comment by PJ-Finlay** [comment]
The device setting is configured with the `ARGOS_DEVICE_TYPE` environment variable, currently there's not a great way to directly run from Python besides setting the env variable or installing from [source](https://github.com/argosopentech/argos-translate/blob/61afaf460e0ca775c793065e95c99857780c8c5d/argostranslate/settings.py#L107).

Hopefully in the future we can add a way to load settings from multiple sources.

**Comment by fcolecumberri** [comment]
That's a shame, thanks.
