### ISSUE TITLE
Do Screenshots on a Qt based Distro

### ISSUE THREAD

**Issue by fossdd** [argosopentech/argos-translate#22]
Screenshots promoted by argos are token from a GNOME display manager. Gnome itself has not the best integration with Qt. Gnome uses Gtk.

Maybe take these screenshots on a display manger with a better Qt integration like KDE Plasma.

**Comment by PJ-Finlay** [comment]
Can you make a pull request, I'll look at it? One reason to potentially keep Gnome is that most of the users current are from Snapcraft/Ubuntu which defaults to Gnome
