### ISSUE TITLE
Worse performance with retrained models?

### ISSUE THREAD

**Issue by PalmerAL** [argosopentech/argos-translate#221]
(Not sure if this should go here or in `argospm-index`; I can move if you want)

I started updating the model files on my LibreTranslate instance today from a version from several months ago, and I'm noticing that at least for the DE -> EN model, the performance of the 1.5 model seems worse than the old 1.0 model. Some text examples:

A paragraph from https://de.wikipedia.org/wiki/COVID-19-Pandemie - "Am 13. Januar 2020 trat in Thailand die erste..."

Google translate version:
> The first corona infection outside of China, confirmed by a laboratory test, occurred in Thailand on January 13, 2020, and outside Asia for the first time on January 23, 2020 in the USA. In both cases there was a connection to travel to or from Wuhan. In order to counteract the spread to states without efficient health systems, the WHO declared the coronavirus pandemic on January 30, 2020 to be a "health emergency of international concern". 

1.0 model (mostly right):
> on 13 January 2020, the first Corona infection confirmed by a laboratory test occurred outside China, outside asiens for the first time on 23 January 2020 in the Usa. in both cases there was a connection to travel to or from wuhan. In order to counteract a spread in states without efficient health systems, the who declared the coronavirus pandemic on 30 January and 2020.

1.5 model (nonsensical):
> on 13 and 19th December 2020, in thailand, the first to travel to or from wuhan through a laboratory test confirmed the Corona infection outside China, outside asiens for the first time in the U.a. in both cases, there was a link to travel to or from wuhan. to counteract a proliferation of countries without effective health systems, the latter declared the pandemic of the pandemic to be "health in the world".

https://www.tagesschau.de/ausland/amerika/marcus-lamb-priester-usa-corona-gestorben-101.html - "Immer wieder sprach..."

Google translate:
> Again and again, Marcus Lamb spoke out against the corona vaccination. Opponents of vaccinations and conspiracy theorists had their say on his television station. Now the US preacher has died after suffering from Covid. 

1.0 model:
> again and again marcus lamb spoke against the corona vaccination. in his television station, vaccinators and conspiracy theorists came to word. The US preacher has now died after a Covid disease.

1.5 model:
> Marcus Cartier said again against the Corona vaccination. in his remote channel, the defendant and the squirrel. The US predator has died after a covid disease.

https://www.spiegel.de/panorama/justiz/panama-polizei-findet-zehn-millionen-dollar-drogengeld-a-19d5f5b8-f13d-4361-a36e-1c858fb6c566 - "Die Behörden..."

Google translate:
> The authorities in Panama have, according to their own statements, confiscated what is "undoubtedly the largest" amount of drug money in the country's history. During a police operation, more than ten million dollars (around 8.9 million euros) in cash were found, the prosecutor said on Thursday (local time). 

1.0 model:
> the authorities in panama have confiscated the amount of drug money in the history of the country, according to their own data “doubtlessly largest”. more than ten million dollars (approximately 8,9 million euros) of cash had been found in police operations, the prosecutor's office announced on Thursday (local time).

1.5 model (misses "confiscated", replaces "drug money" with "drugs", and completely messes up the end):
> the authorities in Panama have confine themselves to the greatest amount of drugs in the history of the country, which is undoubtedly the most doubtful. In a police operation, more than 10 million cash had been found (about 8.9 million euro) and the office was shared at the donner day (current).

In all of these, the 1.0 model isn't perfect, but the 1.5 model seems to be going in the wrong direction. Is there anything that can be done to make the performance closer to the old model?

<strike>If you want to try it out, libretranslate.com seems to still be running on the old models, and I have an instance running with the new ones: translate-api.minbrowser.org.</strike>

**Comment by PJ-Finlay** [comment]
Good to know thanks, it seems like the new German models [we're a downgrade so I reverted](https://community.libretranslate.com/t/new-german-model/99/3).

**Comment by PalmerAL** [comment]
@PJ-Finlay I'm kind of curious (since I don't know much about this) - where do you think the performance difference comes from? In the post you linked, you mentioned using a larger training data set; I'd assume more data = better, but that seems to not be the case here.

**Comment by PJ-Finlay** [comment]
Hard to say, more data generally is better but in this case more reliance on large low quality datasets like WikiMatrix probably caused the decrease in quality.
