### ISSUE TITLE
Language Code Collisions 

### ISSUE THREAD

**Issue by bouldinnathan** [argosopentech/argos-translate#226]
The Language to_codes for Chinese and Czech are both "zh".
The Language to_codes for Arabic and Azerbaijani are both "ar"

argospm search yeilds:

translate-en_ar: en -> ar
translate-en_ar: en -> ar
translate-en_zh: en -> zh
translate-en_zh: en -> zh

[https://raw.githubusercontent.com/argosopentech/argospm-index/main/index.json](url)

Azerbaijani should be "az" and Czech should be "cs".

**Comment by dingedi** [comment]
I've made a PR for Czech [https://github.com/argosopentech/argospm-index/pull/3](https://github.com/argosopentech/argospm-index/pull/3)

**Comment by PJ-Finlay** [comment]
Good catch thanks!
