### ISSUE TITLE
Poor performance

### ISSUE THREAD

**Issue by bergodrake** [argosopentech/argos-translate#232]
Hi,

I would like to deploy argos-translate in an application that uses spark on a databricks cluster, 
But I've noticed that in local the performance are quite poor, as it takes about 12 seconds to translate a string of 3,500 characters, and parallelization is not solving the issue. Moreover, CPU always reaches 100% so it looks like it's CPU-limited.

For the cluster I am using 10 VMs Standard D3_v2 (4 cores, 14Gb memory) 

I haven't tried GPU acceleration, would it dramatically increase the perfomances or it would just be a marginal increment? 
There are other ways to improve the performances?

And the ultimate question:  what would you expect to be the average time to translate such a string?

Thank you

**Comment by PJ-Finlay** [comment]
[CTranslate2 publishes performance benchmarks](https://github.com/OpenNMT/CTranslate2#performance) you can look at to compare hardware. 

In my experience better CPUs with more cores speeds up translation (I use DigitalOcean), and GPUs should speed things up even more.
