### ISSUE TITLE
Any way to use the .argomodel instead of calling from an api?

### ISSUE THREAD

**Issue by wildaces215** [argosopentech/argos-translate#244]
Hi there is there a way to use a .argomodel directly instead of calling from an api? The reason why I ask this is because I want to create an app and be able to embed the actual models themselves. Thanks in advance!

**Comment by dingedi** [comment]
to use .argosmodel you can use argos-translate, if you don't want to use libretranslate (if that's the api you're talking about)

**Comment by PJ-Finlay** [comment]
Argos Translate just does translation in Python without a web API.

If you want a more "bare metal" setup you can run [CTranslate2](https://github.com/OpenNMT/CTranslate2) as a C++ binary. We have a [tutorial on the forum](https://community.libretranslate.com/t/multilingual-translation-with-ctranslate2-and-pre-trained-fairseq-models/178) on doing this with a tokenizer like SentencePiece.
