### ISSUE TITLE
argostranslategui not detected as installed?

### ISSUE THREAD

**Issue by Tarcaxoxide** [argosopentech/argos-translate#246]
running `./LibreTranslate/env/bin/argos-translate-gui`
returns
```
argos-translate-gui not installed
install with `pip install argostranslategui`
```
but i have it installed.
`find -iname 'argostranslategui'`
```
./.local/lib/python3.8/site-packages/argostranslategui
./.local/lib/python3.9/site-packages/argostranslategui
```

version 1.2.7 according to `./Libretranslate/VERSION`
other info about my setup.
```
OS: Gentoo Base System release 2.8 x86_64
Host: ProLiant ML350 G6
Kernel: 5.16.10-zen1-x86_64
Terminal: terminator
CPU: Intel Xeon X5675 (24) @ 3.066GHz
GPU: NVIDIA GeForce GTX 1070 Ti
```

**Comment by Tarcaxoxide** [comment]
version v3.36.0 according to `./LibreTranslate/env/lib/python3.9/site-packages/flask_swagger_ui/dist/VERSION`

**Comment by dingedi** [comment]
I tried under ubuntu (21.10 & 22.04) and I have no problem, maybe it's a problem with gentoo?

**Comment by Tarcaxoxide** [comment]
> I tried under ubuntu (21.10 & 22.04) and I have no problem, maybe it's a problem with gentoo?

I don't think so, since everything is compiled from source.
the only way that would likely be the case is if this package is using something very odd and specific,
in which case why was it not documented so that i can compile my system correctly.

it apparently can't find polyglot either.
however it found the Mi.py i installed just fine and i would think that this would be a similar task.

something else that is weird as well is i manually downloaded the files and then moved them into the temporary directory where 
`./LibreTranslate/install_models.py` downloads the files to and the thing is still attempting to download the files despite them already being there. *shrugs*

**Comment by Tarcaxoxide** [comment]
and if i manually run `./.local/bin/argos-translate-gui` it works.
I've even installed the langauges through this gui but then when i start the web gui
`python LibreTranslate/main.py`
it detects a some of them , like it detects english to japanese but it doesn't detect japanese to english which is really the one i needed XD

**Comment by PJ-Finlay** [comment]
I [deleted](https://github.com/argosopentech/argos-translate/commit/e87a011409892f7ce07229acda68ae6f2bad4f78) this doc executable because it was causing more confusion than helping.
