### ISSUE TITLE
argospm gives no indication of download size and shows no progress

### ISSUE THREAD

**Issue by bruceleerabbit** [argosopentech/argos-translate#255]
This is really annoying for people on measured rate Internet connections.  We only know vaguely how big the lang pair file is because the readme says roughly that they’re all around 100mb.  That’s big enough that the downloader should tell users in advance how big the download will be.  And it’s unnerving that there is no progress indicator to show how much bandwidth is being consumed.  We are trapped because we might have stuff to do… we might have to shutdown and go somewhere.  But with no progress indicator we are forced to wait an indefinite amount of time until the transfer is complete.

When the transfer is complete, the user isn’t even told how much bandwidth was used.  We have to visit the download folder to see how big the file was.

(edit)
Partial workaround: viewing the models in the following location can give a better idea of download size prior to fetching:

https://github.com/argosopentech/LibreTranslate-Models

As for a progress indicator workaround, I wonder if there might a 3rd party utility like socat that can sit in the middle & measure `argospm` progress and report it realtime.

**Comment by PJ-Finlay** [comment]
I don't think there's a good way to get download progress currently:
- https://community.libretranslate.com/t/improving-package-download/213/7

We could expose the download size in the Python library and print it in the CLI.

**Comment by PJ-Finlay** [comment]
If you need live download information you can get the package links from `IPackage.links`and use a library like "Python requests" that has the functionality you need.
