### ISSUE TITLE
Do you offer setup instructions for OFFLINE translation mode? 

### ISSUE THREAD

**Issue by inglesuniversal** [argosopentech/argos-translate#26]
My target platforms are:

Hybrid Apps made with: Monaca or Cordova 

React Native App made with Expo.io

Thanks

**Comment by PJ-Finlay** [comment]
https://github.com/argosopentech/argos-translate/issues/10

**Comment by PJ-Finlay** [comment]
Getting offline translation running on mobile is a hard problem and I haven't done it. If you get anything working please share results. I don't know if this meets your use case but running a local network with libretranslate running on a Raspberry Pi and a web client would be much easier.
