### ISSUE TITLE
Using custom logger to avoid poluting root logger

### ISSUE THREAD

**Issue by pirhoo** [argosopentech/argos-translate#265]
Hello,

I noticed you're configuring logs to the root logger which is generally a bad practice in Python as it can "pollute" other loggers.

I would suggest using a dedicated in [utils.py](https://github.com/argosopentech/argos-translate/blob/master/argostranslate/utils.py):

```python
import logging

from argostranslate import settings

logger = logging.getLogger(__name__) # or replace __name__ by "argostranslate"
logger.setLevel(logging.DEBUG if settings.debug else logging.INFO)

def info(*argv):
    """Info level log"""
    logger.debug(str(argv))


def error(*argv):
    """Error level log"""
    logger.error(str(argv))
```

Let me know if you prefer a PR :) 

Have a great day!

**Comment by PJ-Finlay** [comment]
Using a custom logger namespace seems like a good idea, a pull request would be welcome.

**Comment by PJ-Finlay** [comment]
https://github.com/argosopentech/argos-translate/pull/266
