### ISSUE TITLE
HTML codes appearing in plaintext on the commandline

### ISSUE THREAD

**Issue by bruceleerabbit** [argosopentech/argos-translate#268]
Sometimes the argos-translate output contains a proper apostrophe (’) character, and sometimes it contains the HTML encoding for an apostrophe (“`&apos;`”).  HTML might be okay in the GUI (as it will be converted), but it makes no sense on the commandline where plaintext is expected.

Sample command:
```
argos-translate --from-lang en --to-lang fr "The explanation I gave to the ABC representative left no possibility for misinterpretation."
```
resulting output:
```
L &apos; explication que j &apos; ai donnée au représentant de l &apos; ABC n &apos; a laissé aucune possibilité d &apos; interprétation erronée.
```
It’s inconsistent, but reproducable.  That is, the above sample will show HTML encodings every time, but different input text will sometimes show apostrophes as expected.

The HTML encodings are also surrounded with spaces, which is probably wrong even in HTML.

***(update)***

My workaround is to add this to shell scripts:
```
htmldec()
{
    sed 's/[ ]*[&]\([^;]*\);[ ]*/\&\1;/g' | perl -n -mHTML::Entities -e ' ; print HTML::Entities::decode_entities($_) ;'
}
```
Then pipe argos output through that.  The ugly leading sed code removes the spaces surrounding the HTML entities and the PERL pipeline does the conversion into plaintext. The removal of spaces could have side-effects in the event that characters other than apostrophes come through. But then correcting that can really make for some ugly sed code because double quotes would need a space on one side and not the other, and this would vary between starting quote and ending quote.  Another imperfection with this workaround that is that the PERL replaces `&apos;` with a straight single quote, whereas some of the text already contains a properly curved apostrophe (’), so in the end there is a mix of the two.

**Comment by PJ-Finlay** [comment]
This is the seq2seq model generating bad output. I used to filter html character codes from the data but stopped doing it because it was slow.
