### ISSUE TITLE
Exclude or handle certain patterns differently

### ISSUE THREAD

**Issue by SethFalco** [argosopentech/argos-translate#276]
There are certain patterns in text that probably shouldn't be modified by the translation engine.

For example, all URLs, email addresses, and phone numbers shouldn't be touched.

Current examples:
| English | Dutch | Remarks |
|---|---|---|
| I'm on https://test.com/ | Ik ben op de hoogte |
| My email address is user@example.org | Mijn e-mailadres is gebruiker@example |
| My phone number is +447378099903 | Mijn telefoonnummer is 447378099903 | That `+` is important! |
| This item costs €30. | Dit item kost $30. | `€` != `$` (It shouldn't change currency, nor convert.)

| Dutch | English | Remarks |
|---|---|---|
| Het is 19:30 | It's 7:30 | Creates ambiguity, don't know if morning or afternoon. |

---

I don't know how Google Translate for example handles these specific situations, but it does have support for specifying `notranslate` on text (API only) to avoid translating it which would at least allow clients to work around the issue.

### Google Translate
**Input**
```
My name is Seth, and my Discord username is "i am cool".
```

**Output**
```
Mijn naam is Seth en mijn Discord-gebruikersnaam is &quot;ik ben cool&quot;.
```

**Input**
```
My name is Seth, and my Discord username is "<span class="notranslate">i am cool</span>".
```

**Output**
```
Mijn naam is Seth en mijn Discord-gebruikersnaam is &quot; <span class="notranslate">i am cool</span> &quot;.
```

Notice how text between `<span class="notranslate">…</span>` isn't translated?

You can test the API yourself if you get an API key from Google Cloud Platform.

```http
POST /language/translate/v2?q={}&target=nl&key={} HTTP/1.1
Host: translation.googleapis.com

```

**Comment by dingedi** [comment]
In the same type as [https://github.com/LibreTranslate/LibreTranslate/pull/268](https://github.com/LibreTranslate/LibreTranslate/pull/268)
managing these specific patterns can only be done with better and bigger data as I understand it.

**Comment by PJ-Finlay** [comment]
Yes, it's a tradeoff between trying to manually program behavior to improve translations and making the code more complex and confusing. With Argos Translate I've done very little with manual corrections and tried to just improve the data and the trained model. LibreTranslate does more manual modifications though.

**Comment by SethFalco** [comment]
I see!

And what about the `notranslate` feature?
I guess you'd expect client like LibreTranslate to implement that, not Argos Translate itself?

**Comment by SethFalco** [comment]
Ahhh! Yeah nice! I see it [here](https://github.com/argosopentech/translate-html/commit/cfc8e8296a41ac98ebed70108d49f34415810b02#diff-1e28df2252539b6ed2b9b023697c7b9aa500df738b8798e6f129edceec057ca8R33).

Sorry to spam here then, everything looks good.
