### ISSUE TITLE
Are you open to suggestions about the GUI and features?

### ISSUE THREAD

**Issue by neoOpus** [argosopentech/argos-translate#277]
Hi,

I love this Q-Translate alternative and I am starting to get used to it... I think this can be much better than Q-Translate which seems more like abandonware at this stage...

I would like to compile some ideas about how I think this can borrow some of the great features and what could increase productivity and user-friendliness, but I don't know if you guys are open to suggestions...

**Comment by PJ-Finlay** [comment]
I'm always open to suggestions!

I try to keep GitHub pretty on topic, so only content directly related to features, bugs, and development. I also have a forum for the project where posts of many kinds are encouraged:
https://community.libretranslate.com/c/argos-translate/5
