### ISSUE TITLE
flatpak for argos-translate

### ISSUE THREAD

**Issue by freddii** [argosopentech/argos-translate#28]
It would be useful to have a flatpak for argos-translate at https://flathub.org/home .

**Comment by PJ-Finlay** [comment]
https://github.com/argosopentech/argos-translate/issues/10

I'm not very familiar with Flatpak and have focused on Snapcraft, but this would be a very welcome contribution if you're interested!

**Comment by freddii** [comment]
i don't know how to do that. but maybe someone else will pick that up :)

**Comment by PJ-Finlay** [comment]
Closing this, discuss Flatpak on main platforms issue.
