### ISSUE TITLE
Bug: Hebrew is not automatically recognised

### ISSUE THREAD

**Issue by TJonCooper** [argosopentech/argos-translate#284]
I've been testing the experimental auto-detection feature (via Libretranslate), and found that it fails to correctly identify Hebrew:

![Screenshot from 2022-08-28 19-23-53](https://user-images.githubusercontent.com/15924377/187084406-cfb867ae-0bff-4c18-9b9a-53eedb53fc59.png)

But translates just fine if Hebrew is explicitly selected:

![Screenshot from 2022-08-28 19-23-59](https://user-images.githubusercontent.com/15924377/187084414-3eb32c79-744e-4bf0-b392-831a38b82232.png)

**Comment by PJ-Finlay** [comment]
I think this is an issue with [polyglot](https://pypi.org/project/polyglot/) which is the library LibreTranslate uses to detect languages. Argos Translate doesn't currently support detecting languages or translating from the "auto" language.
