### ISSUE TITLE
[feature request] copy and paste clipboard in gui

### ISSUE THREAD

**Issue by freddii** [argosopentech/argos-translate#29]
It would be handy to have buttons to:
1)  paste text from clipboard into the gui for translation
2) copy text from translation into clipboard
![copy-paste](https://user-images.githubusercontent.com/7213207/106755717-bc620000-662e-11eb-97c3-3f1a8e2877f8.png)

**Comment by PJ-Finlay** [comment]
Thanks for the interest but I don't think this is worth cluttering the GUI for. LibreTranslate does this for the web GUI but I've tried to keep the Desktop GUI minimalist for usability. This increases the GUI buttons by 40% (5 -> 7) when most users are already pretty comfortable copy/pasting without having to find a button for it.

**Comment by freddii** [comment]
Yes. Will try the web-gui
