### ISSUE TITLE
FileNotFoundError argos-translate/index.json

### ISSUE THREAD

**Issue by AnkS4** [argosopentech/argos-translate#291]
get_available_packages() is returning the error:
version: argostranslate-1.7.0

`available_packages = argostranslate.package.get_available_packages()`

```
Traceback (most recent call last):
  File "/home/anks/miniconda3/envs/stealth/lib/python3.8/site-packages/argostranslate/package.py", line 281, in get_available_packages
    with open(settings.local_package_index) as index_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/anks/.local/cache/argos-translate/index.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 8, in <module>
    available_packages = argostranslate.package.get_available_packages()
  File "/home/anks/miniconda3/envs/stealth/lib/python3.8/site-packages/argostranslate/package.py", line 306, in get_available_packages
    raise Exception(
Exception: Local package index not found, use package.update_package_index() to load it
```

**Comment by armanexplorer** [comment]
As the exception's last line says, you have to call `update_package_index()` before calling `get_available_packages()` for the first time:
```python
import argostranslate.package

argostranslate.package.update_package_index()
available_packages = argostranslate.package.get_available_packages()
```

**Comment by AnkS4** [comment]
Now getting new error:

---> 17 translatedText = argostranslate.translate.translate("Hello World", from_code, to_code)

AttributeError: module 'argostranslate.translate' has no attribute 'translate'

**Comment by armanexplorer** [comment]
Do this instead of using `argostranslate.translate.translate` (all of these lines are required):
```python
installed_languages = argostranslate.translate.get_installed_languages()
from_lang = list(filter(
    lambda x: x.code == from_code,
    installed_languages))[0]
to_lang = list(filter(
    lambda x: x.code == to_code,
    installed_languages))[0]
translation = from_lang.get_translation(to_lang)
translatedText = translation.translate("Hello World!")
print(translatedText)
# '¡Hola Mundo!'
```
----
Note: This incompatibility between the `Examples` and the usage origins from the fact that `Examples` are based on the last version of the repository, not the PyPI version. So, if you want just to follow the examples, you should uninstall the PyPI version and install this package from the repository like this:
```bash
git clone https://github.com/argosopentech/argos-translate.git
cd argos-translate
pip install -e .
```

**Comment by pinakipatrapro** [comment]
Similar issue 
https://github.com/argosopentech/argos-translate/issues/336
