### ISSUE TITLE
OpenCL for AMD / Intel GPUs?

### ISSUE THREAD

**Issue by poVoq** [argosopentech/argos-translate#296]
Is it possible to use OpenCL with AMD or Intel GPUs?

What about some of these AI accellerators found on ARM SoCs?

**Comment by Doomsdayrs** [comment]
For anyone digging, here is the ctranslate2 issue for such support: https://github.com/OpenNMT/CTranslate2/issues/1072

**Comment by killmetohell** [comment]
it has been merged by looks of it https://github.com/OpenNMT/CTranslate2/pull/1989 they also have binaries if it helps.
