### ISSUE TITLE
Return funny character from Argos translation.

### ISSUE THREAD

**Issue by minhanh1234** [argosopentech/argos-translate#299]
I try to translate the following from ru to en

2022-03-19	13:34:33	God	буквально час два и все будет у вас)
2022-03-19	13:34:41	fdsfgs	да, я видел :)

and i am getting the following results.

♪
♪

or sometime i would get 

_
_

Would anyone know why i am getting the following result?
Thanks

**Comment by pierotofy** [comment]
It might be that the Russian model needs some better training data.

**Comment by minhanh1234** [comment]
Agree but it seem be only 1 character in the phrase yhat would crap the entire line. Which it would at least return the un-translated version instead of a funny character or symbol

**Comment by PJ-Finlay** [comment]
Sometimes it generates nonsensical output; the fix is just to train better models.
