### ISSUE TITLE
Command-line Usage

### ISSUE THREAD

**Issue by fleschutz** [argosopentech/argos-translate#3]
Would it be possible to support command-line usage? I searched the documentation but found nothing. I would like to automate translating texts and also text files into multiple languages.

As an example I suggest the following:
argos-translate -text "Hello World!" -from en -to de
argos-translate -file Novel.txt -from en -to de

**Comment by PJ-Finlay** [comment]
Thanks for the issue, this is something I've been meaning to add for a while and [I just pushed a basic cli](https://github.com/argosopentech/argos-translate/commit/028195386aa2fe65936e051b5651ae972009f9d6).

Usage:
    $ argos-translate-cli --from-lang en --to-lang es "Hello World"
    Hola Mundo

I'm going to wait a bit before before pushing this to PyPI or the Snap Store so for now if you want to use it you'll need to install from source. Before pushing there should also be the ability to read text from standard input and install packages.

Any feedback on the API before it's too set in stone is also appreciated.

**Comment by v217** [comment]
A cli UI would also make a pipx installation meaningful - the easiest, most user friendly way to manage python packages.

**Comment by PJ-Finlay** [comment]
@v217  I agree the plan is to push this to PyPI. I already added the CLI executable as a script in setup.py so pushing to PyPI wouldn't require a code change. I've just been waiting until the CLI was more complete and stable but if someone needs the CLI from PyPI I could push it sooner. You can also install the bleeding edge version from the Github repo with pip in one line:

    pip3 install git+https://github.com/argosopentech/argos-translate

Maybe the documentation should be updates to show this instead of the more verbose example that is currently there. However, if someones new to the command line has the one command version fail they may have an easier time debugging the existing version.

**Comment by v217** [comment]
@PJ-Finlay Great! For me only the funcionality in the example would be very useful and I don't mind if the cli interface changes. I think, people who use argos-translate in their scripts use the library, and for interactive use cli interface changes don't matter.

**Comment by PJ-Finlay** [comment]
@v217 thanks for the input, I'll push a new version with the current code. There's currently a lot of incoming traffic from Hacker News (Github stars have almost doubled in the last 6 hours) so I'm going to wait a day or so to avoid the risk of actually pushing a breaking change.

**Comment by v217** [comment]
@PJ-Finlay Great Thanks!

**Comment by PJ-Finlay** [comment]
We're live! I realized Snapcraft was a little more involved so I'm waiting on it for now but live on PyPI.

https://github.com/argosopentech/argos-translate/commit/0ae69e010da06cf7a5858c410ad72bddf131b9a8

**Comment by v217** [comment]
Works great with pipx! Thanks!

**Comment by cirosantilli** [comment]
It would be really good to add input from a file BTW as proposed by OP:

```
argos-translate-cli -file Novel.txt -from en -to de
```

Pasting long text on the CLI is too error prone as mentioned at: https://askubuntu.com/questions/380847/is-it-possible-to-translate-words-via-terminal/1309774#1309774

**Comment by PJ-Finlay** [comment]
```
$ argos-translate-cli --from-lang en --to-lang es "Hello World"
Hola Mundo

$ echo "Text to translate" | argos-translate-cli --from-lang en --to-lang es
Texto para traducir
```

**Comment by Mkishore1** [comment]
Hello everyone when i try o run the command 
$argos-translate-cli --from-lang en --to-lang es "Hello World" 
I receive an error 

Traceback (most recent call last):
  File "/home/aimscs/.local/bin/argos-translate-cli", line 5, in <module>
    cli.main()
  File "/home/aimscs/.local/lib/python3.6/site-packages/argostranslate/cli.py", line 38, in main
    from_lang = installed_languages[from_lang_index]
TypeError: list indices must be integers or slices, not NoneType
 
how to resolve this

**Comment by PJ-Finlay** [comment]
Do you have the English and Spanish models installed? We should probably add a more helpful error message for when this happens.
