### ISSUE TITLE
Upgrade to CTranslate2 v3.0.0

### ISSUE THREAD

**Issue by dingedi** [argosopentech/argos-translate#302]
[CTranslate2 v3.0.0](https://github.com/OpenNMT/CTranslate2/releases/tag/v3.0.0) has been released, maybe we should update it for argos v2?

**Comment by PJ-Finlay** [comment]
Yeah I've done some experimenting with OpenNMT v3. I'm not going to upgrade now but will for Argos Translate v2.

For development I've started using the `v2` branch almost exclusively at this point which will eventually become Argos Translate 2.0. The version 1 code is mostly frozen but I'm still pretty happy with it so I probably won't upgrade until sometime next year.
