### ISSUE TITLE
python example does not work

### ISSUE THREAD

**Issue by r-shf** [argosopentech/argos-translate#305]
Hello,
The python code written in the documentation does not work:

translatedText = argostranslate.translate.translate("Hello World", from_code, to_code)

Here is the error:

AttributeError: module 'argostranslate.translate' has no attribute 'translate'. Did you mean: 'ctranslate2'?

Thanks.

**Comment by r-shf** [comment]
Fixed by P.J. Thanks.

import argostranslate.package, argostranslate.translate

from_code = "en"
to_code = "es"

# Download and install Argos Translate package
available_packages = argostranslate.package.get_available_packages()
available_package = list(
    filter(
        lambda x: x.from_code == from_code and x.to_code == to_code, available_packages
    )
)[0]
download_path = available_package.download()
argostranslate.package.install_from_path(download_path)

# Translate
installed_languages = argostranslate.translate.get_installed_languages()
from_lang = list(filter(
        lambda x: x.code == from_code,
        installed_languages))[0]
to_lang = list(filter(
        lambda x: x.code == to_code,
        installed_languages))[0]
translation = from_lang.get_translation(to_lang)
translatedText = translation.translate("Hello World!")
print(translatedText)

**Comment by PJ-Finlay** [comment]
https://github.com/argosopentech/argos-translate/issues/298

Thanks for the heads up! I released Argos Translate 1.7.4 where this example is now supported.

I also temporarily made but ultimately [reverted](https://github.com/argosopentech/argos-translate/commit/fd65e2fe46224ef150406682beb1893aca48ca9c) a README fix.
