### ISSUE TITLE
Show loading indicator while installing models

### ISSUE THREAD

**Issue by PJ-Finlay** [argosopentech/argos-translate#31]
Installing a large number of models requires unzipping them which can take a while. A loading indicator should be shown so that users don't think the program has frozen.

**Comment by pierotofy** [comment]
If implemented at the library level, a callback with progress information could be a good idea so that stdout is not polluted.

**Comment by PJ-Finlay** [comment]
This is implemented using QThreads: [https://github.com/argosopentech/argos-translate/commit/75b41acc423d89d0e9648e35afc42f96ac5172ed](https://github.com/argosopentech/argos-translate/commit/75b41acc423d89d0e9648e35afc42f96ac5172ed)

Library users can use the `WorkerThread` `QThreads` helper in `utils` coming in 1.2 for threading but for running Argos Translate on a server you probably want to split translations over multiple processes and utilizing multiple GPUs.

https://github.com/argosopentech/argos-translate/commit/a91d00783319ebeb0f8f134f5e8a8aba2dcc61b4
