### ISSUE TITLE
Translation from English to Catalan hallucinates often 

### ISSUE THREAD

**Issue by jordimas** [argosopentech/argos-translate#312]
How to reproduce, clean installation doing:
*  pip install argostranslate
* argos-translate --from en --to ca < text.txt

See a sample below. _The test "© 2019 Màrqueting digital de BookingSuite"_ is not present in the English sample. 

The models trained at Softcatalà with the same corpus do not show this problem.

### English text

"A new policy now prohibits linking to other social media in any way, including (but not limited to!) fediverse / #Mastodon URLS. I will not participate in an explicitly walled garden.

**help.twitter.com/en/rules-and-...**

Those who stay are putting themselves at risk, and I tried to sound the warning for weeks. I'm done. It's nicer here"

### Catalan text

"Una nova política prohibeix ara la vinculació amb altres xarxes socials de qualsevol manera, incloent (però no limitat a!) fediverse / #Mastodon URLS. No participaré en un jardí de paret explícita.

**© 2019 Màrqueting digital de BookingSuite. BookingSuite és una marca de Booking.com. Estaràs en bones mans: pots confiar en el gran servei d'Atenció al client que proporciona Booking.com**

Els que s'allotgen es posen en risc, i he intentat sonar l'avís durant setmanes. He acabat. És més bonic

**Comment by splaGit** [comment]
And other one:

**English text**

"Does it pay to pay? A comparison of the benefits of open-access publishing across various sub-fields in Biology | bioRxiv"

**Catalan text**

"Paga? BioRxiv"
