### ISSUE TITLE
Some results duplicated

### ISSUE THREAD

**Issue by derekantrican** [argosopentech/argos-translate#316]
Copying from LibreTranslate issue: https://github.com/LibreTranslate/LibreTranslate/issues/351

According to https://libretranslate.com/?source=en&target=tr&q=Hello it seems that Turkish translations are duplicated (eg "Hello" translates to "Merhaba Merhaba" and "Breakfast" translates into "Kahvaltı Kahvaltı")

According to the comments in the above issue, this may affect some other languages too

**Comment by PJ-Finlay** [comment]
Thanks for the report, this is probably fixed by higher quality language models.
