### ISSUE TITLE
Translations with repetitions

### ISSUE THREAD

**Issue by gerardcarbo** [argosopentech/argos-translate#318]
Here some samples:

 never -> nunca jamás nunca jamás nunca jamás nunca jamás nunca jamás jamás nunca jamás nunca jamás nunca jamás nunca jamás nunca jamás nunca jamás nunca jamás nunca jamás nunca jamás jamás nunca jamás nunca jamás nunca jamás nunca jamás jamás nunca jamás nunca jamás nunca jamás jamás nunca jamás jamás jamás jamás jamás jamás jamás jamás jamás jamás jamás jamás jamás jamás jamás jamás jamás jamás jamás jamás jamás jamás jamás jamás jamás jamás jamás jamás jamás jamás jamás  ....
 anti -> anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti anti ...
 défavorable -> adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse adverse 
 dressed -> vest vestida vest vest vest vest vest vest vest vest vest vest vest vest vest vest vest vest vest vest vest vest vest vest vest vest vest vest vest vest vest vest vest vest vestida vest vest vest vest...
 dramatically -> dramáticamente dramáticamente dramáticamente dramáticamente dramáticamente dramáticamente dramáticamente dramáticamente dramáticamente dramáticamente dramáticamente dramáticamente dramáticamente dramáticamente dramáticamente dramáticamente dramáticamente dramáticamente dramáticamente dramáticamente dramáticamente dramáticamente dramáticamente dramáticamente ...
 disappointed -> decepcion decepcion decepcion decepcion decepcion decepcion decepcion decepcion decepcion decepcion decepcion decepcion decepcion decepcion decepcion decepcion decepcion decepcion decepcion decepcion decepcion decepcion decepcion decepcion decepcion decepcion decepcion decepcion decepcion decepcion decepcion decepcion decepcion decepcion....
 broken -> roto roto roto
 jazz -> jazz jazz jazz jazz jazz jazz jazz jazz
 practical -> prácticas prácticas prácticas
 lifestyle -> estilo de vida estilo estilo de vida estilo estilo estilo de vida estilo estilo estilo de vida
 signal -> señal de señal

**Comment by prowseed** [comment]
Polish to english results into:
```const res = await fetch("https://libretranslate.com/translate", {
	method: "POST",
	body: JSON.stringify({
		q: "auto",
		source: "pl",
		target: "en",
		format: "text",
		api_key: ""
	}),
	headers: { "Content-Type": "application/json" }
});```

```
{
    "translatedText": "auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto auto"
}
```

**Comment by PJ-Finlay** [comment]
https://github.com/LibreTranslate/LibreTranslate/issues/46
