### ISSUE TITLE
Words appear out of the blue?

### ISSUE THREAD

**Issue by santiagobasulto** [argosopentech/argos-translate#319]
Hello, I'm translating subtitles (srt format) from English to Spanish. I see that the model is replacing the `>` character with the word `título` ("title" in Spanish).

For example, original text:

```
1
00:00:00,000 --> 00:00:12,840
Okay, so good morning again, good evening, good afternoon, everyone.
```

Translation:

```
1
00:00:00,000 -- título 00:00:12,840
Buenos días, buenas noches, buenas tardes, todos.
```

Is there any way to avoid this? Thanks!

Edit: furthermore, I replaced the `>` character with a pipe `|` and it translated it to the word "perpetua":

```
1
00:00:00,000 --| 00:00:12,840
Okay, so good morning again, good evening, good afternoon, everyone.
```

```
1
00:00:00,000 -- perpetua 00:00:12,840
Buenos días, buenas noches, buenas tardes, todos.
```

**Comment by dingedi** [comment]
I think you shouldn't send the whole file for translation but only translate and replace the text

**Comment by PJ-Finlay** [comment]
Yes the Argos Translate models don't reliably maintain formatting characters so you should parse things like this explicitly.
