### ISSUE TITLE
Close in system tray

### ISSUE THREAD

**Issue by fethomm** [argosopentech/argos-translate#32]
Please allow for Argos Translate to close into system tray rather than take up room in the panel.

**Comment by PJ-Finlay** [comment]
Can you give more information? Is this on Windows?

**Comment by fethomm** [comment]
Sorry, this is Linux, specifically Debian Unstable with Plasma desktop.

**Comment by PJ-Finlay** [comment]
Can you send a screenshot? I've focused on Ubuntu 20.04 with Gnome Desktop but PyQt should have pretty good support for most Linux Desktops.

**Comment by fethomm** [comment]
Sure, here it is. 
![argos](https://user-images.githubusercontent.com/15143037/107158414-109c1580-698a-11eb-9f50-b17fa9bff06e.png)

**Comment by PJ-Finlay** [comment]
This seems like more of a Plasma Desktop/PyQt issue.
