### ISSUE TITLE
Vietnamese

### ISSUE THREAD

**Issue by lolohoang123** [argosopentech/argos-translate#320]
### Discussed in https://github.com/argosopentech/argos-translate/discussions/91

<div type='discussions-op-text'>

<sup>Originally posted by **PJ-Finlay** April 22, 2021</sup>
Thread for language requests.

Rules:
- Top level comments only names of languages
- Don't duplicate top level comments
- Upvote the language models you want to use to gauge demand

Use [Argos Train](https://github.com/argosopentech/argos-train) to train your own packages. Custom trained models [are available](https://github.com/argosopentech/argos-translate#services) for $1000/each.</div>

**Comment by lolohoang123** [comment]
Vietnamese please

**Comment by PJ-Finlay** [comment]
I used to support Vietnamese but had to remove it because of a [bug in Stanza](https://community.libretranslate.com/t/error-doing-stanza-sentence-boundary-detection-in-vietnamese/289). Vietnamese probably won't be supported until Argos Translate 2.0 when I deprecate Stanza.

**Comment by lolohoang123** [comment]
Thanks for your response,  I look forward to Argos Translate 2.0.

**Comment by rodion-m** [comment]
@PJ-Finlay Hey, what about Vietnamese language support for today? I think it costs to open the issue since it's still not solved.
