### ISSUE TITLE
Bug (?): returning worst instead of best hypotheses for Composite Translation

### ISSUE THREAD

**Issue by mvolfik** [argosopentech/argos-translate#328]
I was browsing through the code, and I noticed that for CompositeTranslation you are sorting the hypotheses by score, and then return the first n of them. However, sorting is by default lowest to highest. I understand little about ML, but from casual observation the scores seem more negative (i.e. lower) for worse results, so the code probably selects the worst combinations.

Just adding a line with `to_sort.reverse()` after the sort call would fix it

https://github.com/argosopentech/argos-translate/blob/23be8352e0ba38d01b901fa4b32d96a3fea196e0/argostranslate/translate.py#L240-L250

**Comment by PJ-Finlay** [comment]
Woops! Good catch thanks

```
import argostranslate.package
import argostranslate.translate

from_code = "de"
to_code = "es"

# Translate
installed_languages = argostranslate.translate.get_installed_languages()
from_lang = list(filter(
        lambda x: x.code == from_code,
        installed_languages))[0]
to_lang = list(filter(
        lambda x: x.code == to_code,
        installed_languages))[0]
translation = from_lang.get_translation(to_lang)
hypotheses = translation.hypotheses("Die Mitglieder der weltweit verbreiteten Familie der Wolfspinnen sind langbeinig und kräftig gebaut. ")
print(hypotheses)

```

```
[('Los miembros de la familia extendida del mundo de las arañas de lobo son de larga distancia y poderosos.', -18.441304206848145), ('Los miembros de la familia extendida del mundo de las arañas de lobo son de larga duración y poderoso.', -18.280563354492188), ('Los miembros de la familia extendida del mundo de las arañas de lobo son de larga duración y poderosos.', -18.15042495727539), ('Los miembros de la familia extendida del mundo de arañas de lobo son de larga distancia y fuertes.', -17.9514217376709)]
```

Fortunately I don't think the impact is very large in most cases. Most of the time this is called with `num_hypotheses=1` so this wouldn't matter. It also looks like most of the hypotheses are pretty close in quality.
