### ISSUE TITLE
Addition of the M2M-100 language models

### ISSUE THREAD

**Issue by michaelfeil** [argosopentech/argos-translate#342]
M2M is MIT-Licensed.
https://huggingface.co/facebook/m2m100_1.2B

I worked with it, while adding a small utility here supporting the Ctranslate2 framwork, https://huggingface.co/michaelfeil/ct2fast-m2m100_1.2B/blob/main/README.md
It works in around 1.5GB VRAM and produces often on-par results to OpenNMT models, while it can also serve as a fallback if a specific model for a language pair is not loaded. It might also be helpful, if a translation from dk->no is not loaded and needs to go via english, which might produce poor quality.

**Comment by PJ-Finlay** [comment]
M2M-100 is available with with Argos Translate 2 beta (GitHub `v2` branch) by default.

I copied the CTranslate2 model generated by ymoslem into the argospm packaging system.

https://github.com/argosopentech/argospm-index/blob/f63f0c7dda3d8045b4ef589fa89f8c16717fa4a7/index.json#L21

https://community.libretranslate.com/t/multilingual-translation-with-ctranslate2-and-pre-trained-fairseq-models/178/27

**Comment by michaelfeil** [comment]
This is amazing, thank you very much @PJ-Finlay
