### ISSUE TITLE
Upgrade/Be more flexible with ctranslate2 version?

### ISSUE THREAD

**Issue by junchen6072** [argosopentech/argos-translate#357]
Hi, I want to use faster-whipser and argos in the same image, but the ctranslate2 version for faster-whisper is pretty ahead of args, which is ctranslate2>=3.17 vs ctranslate2==2.24.0

I tried both with ctranslate2 with 3.17 and it seems fine. Can we upgrade ctranslate2 here? Thanks!

**Comment by hilderonny** [comment]
The same here. We use this combination for transcribing audio files with faster-whisper and translating the english result into different languages.

Best regards

**Comment by PJ-Finlay** [comment]
CTranslate2 is now version `3.20.0`

I try to use an updated version of CTranslate2 so if this falls behind again please make a pull request.
