### ISSUE TITLE
Remote cloud translations

### ISSUE THREAD

**Issue by PJ-Finlay** [argosopentech/argos-translate#38]
Support connecting to a remote LibreTranslate server for translations you don't have locally.

**Comment by pierotofy** [comment]
It would be cool to have a small independent Python library (a simple module around `requests`?) that can do this, then simply import it into argos.

**Comment by virtadpt** [comment]
That would also make it easy for folks to run Argos on a fairly powerful server remotely, but send requests from a less powerful machine over a VPN connection.

**Comment by PJ-Finlay** [comment]
This probably makes the most sense as LibreTranslate Python bindings similar to what exists for Rust and C#.

**Comment by PJ-Finlay** [comment]
Done!

https://github.com/argosopentech/LibreTranslate-py
