### ISSUE TITLE
Feature Request: Allow installing without `nvidia-cuda` packages.

### ISSUE THREAD

**Issue by sohang3112** [argosopentech/argos-translate#389]
When I install `pip install argostranslate`, various `nvidia-cuda` packages are also installed automatically. 
But I don't need these, since I am not using NVIDIA CUDA.

I suggest that 2 packages be made available for install: one with cuda support: `argostranslate[cuda]` and one without: `argostranlate[no-cuda]`. 
To avoid breaking changes, we can make the default `argostranslate` same as `argostranslate[cuda]` - that is, cuda packages will be installed, unless we explicitly opt out by using `argostranslate[no-cuda]`.

This will help to reduce time taken in installing `argostranslate`, which is quite helpful, especially in Docker.

**Comment by sohang3112** [comment]
Also, `nvidia` package (2.8G in Python site packages) is installed, which is not required because I'm not running on NVIDIA hardware.

**Comment by sohang3112** [comment]
NVIDIA packages are installed due to `ctranslate2` package (only on Linux, x64 platform).

```json
"nvidia-cuda-nvrtc-cu12 ==12.1.105 ; platform_system == \"Linux\" and platform_machine == \"x86_64\"",
"nvidia-cuda-runtime-cu12 ==12.1.105 ; platform_system == \"Linux\" and platform_machine == \"x86_64\"",
"nvidia-cuda-cupti-cu12 ==12.1.105 ; platform_system == \"Linux\" and platform_machine == \"x86_64\"",
"nvidia-cudnn-cu12 ==8.9.2.26 ; platform_system == \"Linux\" and platform_machine == \"x86_64\"",
"nvidia-cublas-cu12 ==12.1.3.1 ; platform_system == \"Linux\" and platform_machine == \"x86_64\"",
"nvidia-cufft-cu12 ==11.0.2.54 ; platform_system == \"Linux\" and platform_machine == \"x86_64\"",
"nvidia-curand-cu12 ==10.3.2.106 ; platform_system == \"Linux\" and platform_machine == \"x86_64\"",
"nvidia-cusolver-cu12 ==11.4.5.107 ; platform_system == \"Linux\" and platform_machine == \"x86_64\"",
"nvidia-cusparse-cu12 ==12.1.0.106 ; platform_system == \"Linux\" and platform_machine == \"x86_64\"",
"nvidia-nccl-cu12 ==2.19.3 ; platform_system == \"Linux\" and platform_machine == \"x86_64\"",
"nvidia-nvtx-cu12 ==12.1.105 ; platform_system == \"Linux\" and platform_machine == \"x86_64\"",
"triton ==2.2.0 ; platform_system == \"Linux\" and platform_machine == \"x86_64\"",
```

Found this info by running `pip install --dry-run --ignore-installed argostranslate --report argos_deps.json` in Python 3.8 environment. Found above NVIDIA dependencies in key `"requires_dist":` of dict of `ctranslate2` dependency in *argos_deps.json*.

[argos_deps.json](https://github.com/argosopentech/argos-translate/files/14235680/argos_deps.json)

**Comment by sohang3112** [comment]
Also, `argostranslate REQUIRES stanza REQUIRES torch` and `torch` requires NVIDIA libraries (eg. libcublas.so)

**Comment by PJ-Finlay** [comment]
I haven’t tried it but I think it should be possible to install Argos Translate without all of the (very large) Nvidia dependencies by disabling them for both CTranslate2 and Stanza.

https://community.libretranslate.com/t/using-argos-translate-without-nvidia-dependencies/1061
