### ISSUE TITLE
Filter HTML entities in training scripts data

### ISSUE THREAD

**Issue by quentin-bettoum** [argosopentech/argos-translate#39]
Hello, I've noticed a bug when translating something to French.
Sometime, there is the HTML entity `&apos;`  appearing instead of the apostrophe.
Some examples:
![argos-translate1](https://user-images.githubusercontent.com/63603941/108377773-a8a8c300-7204-11eb-8c57-e310c220077c.png)
![argos-translate2](https://user-images.githubusercontent.com/63603941/108377790-ab0b1d00-7204-11eb-830f-054150a67490.png)
![argos-translate5](https://user-images.githubusercontent.com/63603941/108378590-6df35a80-7205-11eb-8e9f-78562e2e6e09.png)

Though it doesn't happen in these cases
![argos-translate4](https://user-images.githubusercontent.com/63603941/108377931-d130bd00-7204-11eb-89a6-bd8ebd8481ce.png)
![argos-translate3](https://user-images.githubusercontent.com/63603941/108377927-d0982680-7204-11eb-8718-4eb2c4993f1a.png)

**Comment by PJ-Finlay** [comment]
Interesting, good catch. I was able to reproduce this. The tokenization looks fine so the sequence to sequence model is just outputting HTML characters. The training data (OpenSubtitles, ParaCrawl, UNPC from OPUS) is generally created by scraping real world data so I'm guessing some escaped HTML codes made their way into the training data. It might make sense to add a filter in the training scripts to filter out any lines that have HTML escape codes in them.

**Comment by PJ-Finlay** [comment]
This should be done for any models trained going forward. 
```
html_entities = ['&apos;', '&nbsp;', '&lt;', '&gt;', '&quot;']
html_tags = ['<a>', '<p>', '<h1>', '<i>']
```
Suggestions for additional things that might be in training data to filter appreciated.

**Comment by pierotofy** [comment]
You could also use: https://docs.python.org/3/library/html.html#html.unescape

And a regex or beautifulsoup https://stackoverflow.com/questions/9662346/python-code-to-remove-html-tags-from-a-string

Which would make it more generic.

**Comment by PJ-Finlay** [comment]
That might make sense but for now I'm just removing data that has one of these strings instead of trying to clean it up.

**Comment by Qix-** [comment]
Still seeing this on models downloaded fresh today, was there perhaps a regression?

qix-/bellingbot#2 has some sample text; RU->EN.

**Comment by PJ-Finlay** [comment]
I ended up removing this filtering because it substantially slowed down training. I'm still looking it a better solution but hoping that better quality models in general will do this less.
