### ISSUE TITLE
ERROR: Can't pickle ctranslate2.translator.Translator objects

### ISSUE THREAD

**Issue by georchat** [argosopentech/argos-translate#41]
Hi,

Thank you for the great project!

I am using argos translate in my project. I have created a customized sklearn transformer where I call the argos models for translation. My customized transformer is part of sklearn pipeline. However, when I set the pipeline hyperparameter n_jobs to a value higher than 1, I receive the error:

TypeError: can't pickle ctranslate2.translator.Translator objects

Any ideas/advice how I can solve this issue? Are you planning to make ctranslate2 objects picklable?

Thanks again!

**Comment by PJ-Finlay** [comment]
I'm not very familiar with the details of pickling or CTranslate, @guillaumekln any ideas?

**Comment by guillaumekln** [comment]
Pickling `ctranslate2.Translator` instances are not supported.

I'm not familiar with sklearn. How is this pipeline defined and used? Can you build a separate translator in each of these jobs instead of passing a single translator by argument?

**Comment by georchat** [comment]
I
