### ISSUE TITLE
Segmentation fault when running from either cli or Python

### ISSUE THREAD

**Issue by NSBum** [argosopentech/argos-translate#42]
`[1]    91775 segmentation fault  sudo argos-translate-cli --from-lang en --to-lang ru "Hello."`

No problems with installation of models. Models enumerate properly, etc.

**Comment by PJ-Finlay** [comment]
Try:
```
export DEBUG=1
argos-translate-cli --from-lang en --to-lang ru "Hello."
```

This could be an issue with Stanza, SentencePiece, or CTranslate.

**Comment by NSBum** [comment]
`[1]    92056 segmentation fault  sudo argos-translate-cli --from-lang en --to-lang ru "Hello."`

after `export DEBUG=1; argos-translate-cli --from-lang en --to-lang ru "Hello."`

**Comment by PJ-Finlay** [comment]
Interesting but not very helpful. I just pushed some additional debug statements so if you install from source it might print something more useful. You can also try running a translation from Python to see where it crashes which might give some clues.
