### ISSUE TITLE
Documentation mentions ARGOS_TRANSLATE_PACKAGE_DIR but it does not work

### ISSUE THREAD

**Issue by Acly** [argosopentech/argos-translate#435]
The documentation mentions `ARGOS_TRANSLATE_PACKAGE_DIR` environment variable:
https://argos-translate.readthedocs.io/en/latest/source/argostranslate.html#argostranslate.package.get_installed_packages
https://github.com/argosopentech/argos-translate/blob/master/argostranslate/package.py#L313

This seems to be a) outdated and b) have a typo. See [settings.py](https://github.com/argosopentech/argos-translate/blob/master/argostranslate/settings.py#L23) where the environment variable is still supposed to be supported as "legacy", but doesn't match (uses plural `PACKAGES`).

**Comment by argosopentech** [comment]
Good catch thanks!
