### ISSUE TITLE
argos-translate score value not understood

### ISSUE THREAD

**Issue by FWERME** [argosopentech/argos-translate#442]
The **score** value in [argos-translate/argostranslate/translate.py at master · argosopentech/argos-translate · GitHub](https://github.com/argosopentech/argos-translate/blob/master/argostranslate/translate.py)

```
class Hypothesis:
    """Represents a translation hypothesis

    Attributes:
        value: The hypothetical translation value
        score: The score representing the quality of the translation
    """
```
**Question**:
_How is it defined / how does it translate to a aconfidence in [0, 1]?_

**Comment by PJ-Finlay** [comment]
https://community.libretranslate.com/t/log-probability-translation-scores/1505
