### ISSUE TITLE
GPU Support

### ISSUE THREAD

**Issue by PJ-Finlay** [argosopentech/argos-translate#5]
When I first wrote this [CTranslate](https://github.com/OpenNMT/CTranslate2), which does inference, didn't support GPU translation from PyPI. This has since changed and this would be a nice feature to have. All this may take is updating the CTranslate version in requirements.txt and adding documentation but if someone with more CUDA knowledge could look into this I would appreciate it. Also it would be nice to support open-source alternatives to CUDA.

Argos Translate also prints an error message about torch not being able to connect to CUDA:

    /usr/local/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
      return torch._C._cuda_getDeviceCount() > 0

Torch is only used by Stanza which does sentence boundary detection so it supporting GPU inference isn't as important as CTranslate supporting GPUs for performance but this error message should be supressed.

**Comment by PJ-Finlay** [comment]
Haven't tested GPU support but the CTranslate has been updated. If anyone wants to test/document it would be appreciated.

https://github.com/argosopentech/argos-translate/commit/ef7a455895136b67a00248e3ffdcadcbaf5fa379

**Comment by argosopentech** [comment]
[From the OpenNMT author](https://forum.opennmt.net/t/multiple-gpu-for-translation/2940/7?u=argosopentech)

> For a translation server, the recommended approach is to start a server on each GPU and have an external system that does load balancing. This external system is not part of OpenNMT.

**Comment by PJ-Finlay** [comment]
I think CTranslate2 has GPU support.
