### ISSUE TITLE
Emoji translations

### ISSUE THREAD

**Issue by mmokhi** [argosopentech/argos-translate#51]
Using emojis within texts at best gets dropped, and in some cases changes translations to something else.

I know this is a training matter...
But it came to my mind (after some testing and trial-error), that maybe by using _something like_ `.encode("unicode_escape")`* we could let them stay the same (as it often will, so far that I tested) and then afterwards we get it decoded back...

Basically, since we never have to "translate" those characters, I'm thinking maybe we could filter/keep them...

*P.S. not exactly this `encode` statement, but to be figured out :sweat_smile:

**Comment by PJ-Finlay** [comment]
https://github.com/uav4geo/LibreTranslate/issues/33

We should pass through unknown tokens so a better strategy would be to filter emojis in the training scripts.

**Comment by mmokhi** [comment]
> [uav4geo/LibreTranslate#33](https://github.com/uav4geo/LibreTranslate/issues/33)
> 
> We should pass through unknown tokens so a better strategy would be to filter emojis in the training scripts.

Indeed.
I believe this makes more sense than my initial suggestion as well :smile: ,

So filtering them would be like what we do to HTML tokens [here](https://github.com/argosopentech/onmt-models/blob/master/split_train_and_valid.py#L30)?

**Comment by PJ-Finlay** [comment]
Exactly.

**Comment by PJ-Finlay** [comment]
Thanks @mmokhi!

**Comment by mmokhi** [comment]
Thank you too @PJ-Finlay  :smiley: :raised_hands:
