### ISSUE TITLE
Weird english -> japanese translations (bad training data?)

### ISSUE THREAD

**Issue by cbc02009** [argosopentech/argos-translate#58]
I'm using argos-translate via libretranslate, so if this is the wrong place for this, I'll move it.

I'm testing out the english -> japanese translations and I think some bad data might have gotten into the training data. 

"Hello" is being translated as "お問い合わせ" which translates to "Contact Us" (something you'd expect to see at the bottom of a webpage used for training?)

"Goodbye" is being translated as "フィードバック" (feedback). Again, something you'd expect to see at the bottom of a webpage).

"Help me!" is also being translated as "お問い合わせ".

Not exactly sure how I help, but I figured I'd point out the issue.

**Comment by PJ-Finlay** [comment]
I'm aware of this issue but not sure of an exact cause. Single word translations have been a consistent issue: [https://github.com/uav4geo/LibreTranslate/issues/46](https://github.com/uav4geo/LibreTranslate/issues/46)
