### ISSUE TITLE
Auto Code Formatting

### ISSUE THREAD

**Issue by PJ-Finlay** [argosopentech/argos-translate#6]
Ideally there would be some sort of auto code formatting and linting. Related to this there is currently an issue with some of the documentation being formatted:
![image](https://user-images.githubusercontent.com/13067016/102831079-82a3a580-43b0-11eb-8ac1-679f74097289.png)

The goal is to comply with [PEP 8](https://www.python.org/dev/peps/pep-0008/) and [PEP 257](https://www.python.org/dev/peps/pep-0257/) to the extent possible.

**Comment by yogeshwaran01** [comment]
@PJ-Finlay Try [Black](https://github.com/psf/black) to format the python code

**Comment by PJ-Finlay** [comment]
@yogeshwaran01 Can you make a pull request?

**Comment by yogeshwaran01** [comment]
@PJ-Finlay It is a CLI tool
First, install it
```
$ pip install black
```
and then run
```
$ black ~/path/to/file
```
After this, the code will be formatted properly according to with PEP8

**Comment by PJ-Finlay** [comment]
Thanks for the suggestion @yogeshwaran01, very easy!
