### ISSUE TITLE
Add support Persian language

### ISSUE THREAD

**Issue by peylight** [argosopentech/argos-translate#67]
Is it possible to add support for Persian language?

**Comment by PJ-Finlay** [comment]
@mmokhi

**Comment by mmokhi** [comment]
Yep, an initial version is available actually.
I'm just improving it's precision with better inputs (as discussed @PJ-Finlay :grin: )

**Comment by mmokhi** [comment]
@PJ-Finlay If you want I can send over the "so far so good" output now, and we call the newer one with newer version,
wdyt?

**Comment by PJ-Finlay** [comment]
No hurry, I would recommend improving it as much as possible then I'll put it in the package index. If it's going to be a while maybe post a download link in this thread and people can install from file if they want it now.

**Comment by mmokhi** [comment]
Alrighty,
So here is what I have so far [[1]](https://github.com/mmokhi/tradjicore-packs/raw/master/en_fa.argosmodel).
Just for clarification, this result, performs fairly good on long inputs, but has shortcomings on edge/corner cases for shorter phrases (and single vocabularies).

I'm working on it to have cleaner input-data and train it in a better model and dataset (and avoid overtrainings).

I will update y'all with newer version ASAP :crossed_fingers: :blush:

**Comment by mrbooshehri** [comment]
> Alrighty,
> So here is what I have so far [[1]](https://github.com/mmokhi/tradjicore-packs/raw/master/en_fa.argosmodel).
> Just for clarification, this result, performs fairly good on long inputs, but has shortcomings on edge/corner cases for shorter phrases (and single vocabularies).
> 
> I'm working on it to have cleaner input-data and train it in a better model and dataset (and avoid overtrainings).
> 
> I will update y'all with newer version ASAP crossed_fingers blush

Dadash we are waiting for you ha :D
Thx btw

**Comment by jostang** [comment]
@mmokhi Thank you for your work on the Persian translation model! Has there been progress in the mean time?

We build a parent-school-communication app which is used by more than 1400 schools in Germany. Our users include several thousands of refugees from Iran and Afghanistan who would greatly profit if we could automatically translate the schools' information letters to Persian.

**Comment by PJ-Finlay** [comment]
Great to hear about your project! Persian is [widely requested](https://github.com/argosopentech/argos-translate/discussions/91?sort=top#discussioncomment-997821) so I'll hopefully be able to add it soon. I can also add it to the index if anyone else trains the model.

**Comment by PJ-Finlay** [comment]
Not sure about @mmokhi's progress but the process for adding to Argos Translate is to add the data to the [Argos Translate training scripts](https://github.com/argosopentech/argos-train) , train a model, and then add to the [package index](https://www.argosopentech.com/argospm/index/). I can also accept community models directly into the package index.

**Comment by argosopentech** [comment]
[Persian support](https://github.com/argosopentech/argospm-index/commit/101ed9e9ad7b21f01faf44c0970791a150a7fde2) is live on the package index!

**Comment by jostang** [comment]
Wow, that was fast. Thank you very much! We will include the Persian models into our application in the next few days.
