### ISSUE TITLE
How to participate to translation?

### ISSUE THREAD

**Issue by D4708** [argosopentech/argos-translate#68]
I want to fix some translation issues and add new strings, but not understand how can I contribute to the project. Is there any instructions how to change dictionary database? As understand I should operate with https://github.com/argosopentech/onmt-models repository?

**Comment by PJ-Finlay** [comment]
Since it [seems like there's some interest in contributing translations ](https://github.com/argosopentech/argos-translate/discussions/61)a made a git repo where people can contribute:

- [Argos Parallel Corpus](https://github.com/argosopentech/argos-parallel-corpus)

**Comment by D4708** [comment]
Thanks for reply, will learn it.
