### ISSUE TITLE
Better model distribution

### ISSUE THREAD

**Issue by PJ-Finlay** [argosopentech/argos-translate#7]
Currently models are distributed by Google Drive (not ideal) and a slow BitTorrent, so there's lots of room for improvement:
- More Torrent seeders
- Create individual torrent files for each model
- HTTP or FTP mirrors
- I avoided git distribution because I was worried about running into GitHub limits but we may want to link to the [LibreTranslate Git Mirror](https://github.com/uav4geo/LibreTranslate-Models/tree/3d5ca0a2c3c302287339b2944329f767ac1673f4)
- Open to other ideas too

The plan was to make a separate repo for storing model distribution information so let me know if your interested.

**Comment by PJ-Finlay** [comment]
Related to this once better distribution is in place we'll want to add the ability to manage model downloads from the GUI.

**Comment by pierotofy** [comment]
GitHub has (so far, crossing fingers) been pretty good at hosting binary data (up to ~2GB in size per file) without limits, although the party might end sometimes in the future.

Otherwise a central server with CDN works pretty well too. For cheap, there's https://www.digitalocean.com/products/spaces/

**Comment by PJ-Finlay** [comment]
A CDN is probably the best long term solution (in addition to providing torrents) and Google Drive is definitely not ideal. Last weekend when there was a lot of traffic from Hacker News it seems that some people weren't able to download models. I'm tempted to link directly to the githubusercontent url in the [LibreTranslate Models](https://github.com/uav4geo/LibreTranslate-Models) repo but that may increase the chance that we can't continue to use GitHub.

https://stackoverflow.com/questions/38768454/repository-size-limits-for-github-com

**Comment by pierotofy** [comment]
I'm not too worried; the discussion is pre-Microsoft acquisition. If you want to link it, go ahead.

**Comment by davidak** [comment]
There is also [IPFS](https://ipfs.io/).

**Comment by PJ-Finlay** [comment]
@davidak https://www.reddit.com/r/ipfs/comments/l43u9u/seeking_open_source_contribution_to_distribute/

**Comment by Starcommander** [comment]
I wonder if the raw data is also stored anywhere.
Or do we only have the compiled model files?

**Comment by PJ-Finlay** [comment]
No, the training data is very large. I don't even store it myself I just re-download from Opus every time I train a new model. If you're interested in the data go to Opus. There's also a `generate_wiktionary_data.py` script in the training scripts.

**Comment by PJ-Finlay** [comment]
We're now sharing one model pair (English-Chinese) via IPFS (available on [package index](https://www.argosopentech.com/argospm/index/)) as a test. A volunteer is currently pinning  for us and we can expand if people find this useful.

**Comment by user813** [comment]
It might be useful to consider using [GitHub Releases](https://docs.github.com/en/github/administering-a-repository/about-releases) to distribute the models, as there are no bandwidth limitations and since CloudFront is used to deliver the assets.
