### ISSUE TITLE
List license for language models.

### ISSUE THREAD

**Issue by SuperQcid** [argosopentech/argos-translate#76]
I see that this repository is licensed under the MIT license, but the language training models are hosted outside of this repository that can be downloaded with HTTPS, IPFS or torrent. 

Does the same MIT license apply to the models as well, or are they distributed under a different license?

This should probably be listed somewhere.

**Comment by PJ-Finlay** [comment]
Very good question. Any work done by the Argos Translate project towards training models should be considered under the same license as the code (either MIT or CC0). When training models for the package index [we avoid some of the data on OPUS that is under non-commercial restrictions](https://github.com/argosopentech/onmt-models/tree/f7000abd1778eb64dacba2ebccff344f91c4a4d8#making-an-argospm-package), some of the data used is under Creative Commons licenses but a lot of it is created by academics with citation information but no explicit license. 

I think training a ML model on publicly available data should be fair use, but I'm not a lawyer. The strategy has been to just list all of the data used in the README with any available citiations/licenses for transparency and then release models with no restrictions.
