### ISSUE TITLE
Support for emojis in text translation

### ISSUE THREAD

**Issue by fleschutz** [argosopentech/argos-translate#77]
Given is the English text: "Well done 👍"

The text itself gets translated perfectly in any language. However, depending on the target language the emoji is translated to "" or "?" or "Benachrichtigung" (in German).

Would it be possible to detect the emoji and leave that character as it is?
Hint: in Unicode 13.0 there are 4 character ranges allocated for emojis: U+1F300 (127744) to U+1FAD6 (129750), 126980 to 127569, 169 to 174 and 8205 to 12953

**Comment by PJ-Finlay** [comment]
This has already been fixed in the code and should work for any newly trained models going forward.
- https://github.com/argosopentech/argos-translate/issues/51
