### ISSUE TITLE
editing code for GUI Title

### ISSUE THREAD

**Issue by venkat120820** [argosopentech/argos-translate#83]
i want to change title 
but i am changing in GUI.py file but not updated

**Comment by PJ-Finlay** [comment]
You changed this line? I think it should update the tile on the window.

- https://github.com/argosopentech/argos-translate/blob/62271ca643b0521c6986874793f16ff3dbdfa13f/argostranslate/gui.py#L354

**Comment by venkat120820** [comment]
> You changed this line? I think it should update the tile on the window.
> 
>     * https://github.com/argosopentech/argos-translate/blob/62271ca643b0521c6986874793f16ff3dbdfa13f/argostranslate/gui.py#L354

but not reflecting in gui

**Comment by PJ-Finlay** [comment]
I don't know then that should work, maybe also try `setup.py`?

**Comment by PJ-Finlay** [comment]
Related:

- https://github.com/argosopentech/argos-translate/issues/93

**Comment by PJ-Finlay** [comment]
Moving to the forum

- https://github.com/argosopentech/argos-translate/discussions/108
