### ISSUE TITLE
Support for Slovak and/or Czech language

### ISSUE THREAD

**Issue by dammmn** [argosopentech/argos-translate#87]
Is there any plan to support above mentioned languages ? If so, how can I help ?

**Comment by PJ-Finlay** [comment]
Hopefully soon!

We trained a series of models a month or so ago. I'm currently working on some improvements to the code that prepossesses the data before training. I want to wait a bit longer for that to be done before training the next batch. 

I'm also making a thread to discuss language requests:
- https://github.com/argosopentech/argos-translate/discussions
