### ISSUE TITLE
File "/home/.../venv/lib/python3.8/site-packages/argostranslate/translate.py", line 306, in apply_packaged_translation assert(len(sentences) <= BATCH_SIZE)

### ISSUE THREAD

**Issue by bbobox** [argosopentech/argos-translate#97]
Hello,
I get this error  message when i execute translate function with a large text, such as a resume content:

 File "/home/.../venv/lib/python3.8/site-packages/argostranslate/translate.py", line 306, in apply_packaged_translation
    assert(len(sentences) <= BATCH_SIZE)
    
What is the way to get translate result despite the exception?

**Comment by PJ-Finlay** [comment]
It looks like it fails when there are more than 32 sentences. I'll try to fix this before the next release.

- https://github.com/argosopentech/argos-translate/blob/b5a6b833139445f265cdf06e24fe07b3ca8bea0b/argostranslate/translate.py#L370-L380

**Comment by PJ-Finlay** [comment]
This should be fixed in source now

- https://github.com/argosopentech/argos-translate/commit/0827bebb28c10915814ced9b3de9c56b1c25fe5d
